export function getMockData() {
  return {
    properties: [
      { id: 1, name: "Westlands Plaza", location: "Nairobi", units_count: 12 },
      { id: 2, name: "Karen Residences", location: "Nairobi", units_count: 8 },
      { id: 3, name: "Kisumu Heights", location: "Kisumu", units_count: 6 },
    ],
    units: [
      { id: 1, unit_number: "A01", property_id: 1, rent_amount: 15000, status: "occupied" },
      { id: 2, unit_number: "A02", property_id: 1, rent_amount: 15000, status: "occupied" },
      { id: 3, unit_number: "A03", property_id: 1, rent_amount: 15000, status: "vacant" },
      { id: 4, unit_number: "B01", property_id: 1, rent_amount: 20000, status: "occupied" },
      { id: 5, unit_number: "B02", property_id: 1, rent_amount: 20000, status: "occupied" },
      { id: 6, unit_number: "B03", property_id: 1, rent_amount: 20000, status: "occupied" },
      { id: 7, unit_number: "C01", property_id: 2, rent_amount: 18000, status: "occupied" },
      { id: 8, unit_number: "C02", property_id: 2, rent_amount: 18000, status: "vacant" },
      { id: 9, unit_number: "C03", property_id: 2, rent_amount: 18000, status: "occupied" },
      { id: 10, unit_number: "D01", property_id: 3, rent_amount: 12000, status: "occupied" },
      { id: 11, unit_number: "D02", property_id: 3, rent_amount: 12000, status: "occupied" },
      { id: 12, unit_number: "D03", property_id: 3, rent_amount: 12000, status: "vacant" },
    ],
    tenants: [
      {
        id: 1,
        name: "John Kimani",
        phone: "+254712345678",
        id_number: "12345678",
        unit_id: 1,
        move_in_date: "2024-01-15",
      },
      {
        id: 2,
        name: "Sarah Njoki",
        phone: "+254723456789",
        id_number: "87654321",
        unit_id: 2,
        move_in_date: "2024-02-20",
      },
      {
        id: 3,
        name: "Peter Kipchoge",
        phone: "+254734567890",
        id_number: "11223344",
        unit_id: 4,
        move_in_date: "2023-11-10",
      },
      {
        id: 4,
        name: "Mary Wanjiru",
        phone: "+254745678901",
        id_number: "55667788",
        unit_id: 5,
        move_in_date: "2024-03-01",
      },
      {
        id: 5,
        name: "Joseph Kipyegon",
        phone: "+254756789012",
        id_number: "99001122",
        unit_id: 6,
        move_in_date: "2024-01-25",
      },
    ],
    payments: [
      {
        id: 1,
        tenant_id: 1,
        month: "January",
        year: 2025,
        amount: 15000,
        mpesa_code: "ABC123DEF456",
        paid_date: "2025-01-05",
        status: "paid",
      },
      {
        id: 2,
        tenant_id: 2,
        month: "January",
        year: 2025,
        amount: 15000,
        mpesa_code: "XYZ789UVW012",
        paid_date: "2025-01-08",
        status: "paid",
      },
      {
        id: 3,
        tenant_id: 3,
        month: "January",
        year: 2025,
        amount: 20000,
        mpesa_code: "QWE345RTY678",
        paid_date: "2025-01-12",
        status: "paid",
      },
      {
        id: 4,
        tenant_id: 4,
        month: "January",
        year: 2025,
        amount: 20000,
        mpesa_code: "ASG901DFH234",
        paid_date: "2025-01-10",
        status: "paid",
      },
      {
        id: 5,
        tenant_id: 5,
        month: "January",
        year: 2025,
        amount: 20000,
        mpesa_code: "VCX567BNM890",
        paid_date: "2025-01-15",
        status: "paid",
      },
      {
        id: 6,
        tenant_id: 1,
        month: "February",
        year: 2025,
        amount: 15000,
        mpesa_code: null,
        paid_date: null,
        status: "unpaid",
      },
      {
        id: 7,
        tenant_id: 2,
        month: "February",
        year: 2025,
        amount: 15000,
        mpesa_code: "LKJ234QWE567",
        paid_date: "2025-02-08",
        status: "paid",
      },
    ],
    notifications: [
      {
        id: 1,
        title: "Payment received for Unit A01",
        message: "John Kimani paid KES 15,000 for January",
        type: "payment_received",
        status: "unread",
        timestamp: new Date(Date.now() - 3600000),
      },
      {
        id: 2,
        title: "Rent due in 3 days",
        message: "Unit A03 - Peter Kipchoge's rent is due on Feb 28",
        type: "rent_due",
        status: "unread",
        timestamp: new Date(Date.now() - 7200000),
      },
      {
        id: 3,
        title: "Unit C02 is now vacant",
        message: "Karen Residences - Unit C02 became vacant",
        type: "announcement",
        status: "read",
        timestamp: new Date(Date.now() - 86400000),
      },
      {
        id: 4,
        title: "Maintenance scheduled",
        message: "Westlands Plaza - General maintenance on Feb 25",
        type: "announcement",
        status: "read",
        timestamp: new Date(Date.now() - 172800000),
      },
      {
        id: 5,
        title: "Payment received for Unit B01",
        message: "Mary Wanjiru paid KES 20,000 for January",
        type: "payment_received",
        status: "read",
        timestamp: new Date(Date.now() - 259200000),
      },
    ],
  }
}
